// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUz5LVWExJwyrC8nTZkNZTkNwhYeiUpo',
    appId: '1:12231657880:web:132c8b0f80a08ff5fd43ed',
    messagingSenderId: '12231657880',
    projectId: 'volleyball-roster-list',
    authDomain: 'volleyball-roster-list.firebaseapp.com',
    storageBucket: 'volleyball-roster-list.firebasestorage.app',
    measurementId: 'G-Z15HXPBEV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBETy_hT2Ld0cPS7V5opz7fqqB0J6ilVlM',
    appId: '1:12231657880:android:2fba7ad03b99cb96fd43ed',
    messagingSenderId: '12231657880',
    projectId: 'volleyball-roster-list',
    storageBucket: 'volleyball-roster-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC35hijb0KFm5hXfftJr4lkSdfeNRyVsK0',
    appId: '1:12231657880:ios:8e35be53c449cbd0fd43ed',
    messagingSenderId: '12231657880',
    projectId: 'volleyball-roster-list',
    storageBucket: 'volleyball-roster-list.firebasestorage.app',
    iosBundleId: 'com.example.volleyballRosterList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC35hijb0KFm5hXfftJr4lkSdfeNRyVsK0',
    appId: '1:12231657880:ios:8e35be53c449cbd0fd43ed',
    messagingSenderId: '12231657880',
    projectId: 'volleyball-roster-list',
    storageBucket: 'volleyball-roster-list.firebasestorage.app',
    iosBundleId: 'com.example.volleyballRosterList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUz5LVWExJwyrC8nTZkNZTkNwhYeiUpo',
    appId: '1:12231657880:web:896e85c658751f5bfd43ed',
    messagingSenderId: '12231657880',
    projectId: 'volleyball-roster-list',
    authDomain: 'volleyball-roster-list.firebaseapp.com',
    storageBucket: 'volleyball-roster-list.firebasestorage.app',
    measurementId: 'G-0SRRLX26J4',
  );
}
